name: CI

on:
  push:
    branches: [ "main", "simplified" ]
  pull_request:
    branches: [ "main", "simplified" ]

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

#      - name: Cache packages
#        id: cache-vcpkg
#        uses: actions/cache@v3
#        env:
#          cache-name: cache-vcpkg-packages
#        with:
#          path: C:/vcpkg
#          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install packages
        run: >
          vcpkg install --triplet x64-mingw-static --binarysource="clear;x-gha,readwrite"
          libxml2
          capnproto
          boost-program-options
          openssl
          dlfcn-win32
          spdlog

      - name: Configure
        run: cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -B build -G "MinGW Makefiles" .

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

      - name: Run
        run: ./build/main

