name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Setup
#        run: vcpkg install libxml2 capnproto spdlog boost openssl
        run: vcpkg install --triplet x64-windows capnproto

      - name: Configure
        run: cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake  -B build -G "MinGW Makefiles" .

      - name: Build
        run: cmake --build build

      - name: Run
        run: ./build/main

