name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake -B build -H . -G "MinGW Makefiles"

      - name: Build
        run: cmake --build build

